// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvchejoxipjbuqqeelee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Y2hlam94aXBqYnVxcWVlbGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwOTY3MDEsImV4cCI6MjA1MzY3MjcwMX0.Y7lh4PArZzI0JmdcZ24WGCtp1mwJNkxM8Vp5ax6cLTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);